language: java
before_script:
  - psql -c "create database example_app;" -U postgres
  - psql -c "create user example_user with password 's3cr3t';" -U postgres
  - psql -c "grant all on database example_app to example_user;" -U postgres
install:
  - "mvn install"
script: mvn test
after_success: mvn -DperformRelease=true cobertura:cobertura coveralls:cobertura
jdk:
  - oraclejdk8
  - oraclejdk7
